### ISSUE TITLE
failure on new clickhouse install

### ISSUE THREAD

**Issue by gregzuro** [duyet/clickhouse-monitoring#401]
I just installed clickhouse and have done nothing with it, yet.

I point this at that server and get a bunch of errors related to tables that don't (yet) exist:

^query_log
^metric_log
^part_log
^error_log
system.backup_log

**Comment by duyet** [comment]
You will need to enable these system log tables in your settings, for example to enable query_log: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#query-log

```xml
<clickhouse>
    <query_log>
        <database>system</database>
        <table>query_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
        <!--
        <engine>ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) SETTINGS index_granularity = 1024</engine>
        -->
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        <max_size_rows>1048576</max_size_rows>
        <reserved_size_rows>8192</reserved_size_rows>
        <buffer_size_rows_flush_threshold>524288</buffer_size_rows_flush_threshold>
        <flush_on_crash>false</flush_on_crash>
    </query_log>
</clickhouse>
```

- enable `system.query_log`: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#query-log
- enable `system.metric_log`: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#metric_log
- enable `system.part_log`: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#part-log
- enable `system.error_log`: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#error_log

Thank you for letting me know, will update the document.

**Comment by gregzuro** [comment]
> You will need to enable these system log tables in your settings, for example to enable query_log: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#query-log

>     * enable `system.query_log`: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#query-log
> ...

Those worked great.

For completeness, I added backup_log per: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#backup_log

and am (still) getting: 
```
2024.11.11 11:02:46.194035 [ 19193 ] {631ad5d3-602d-4582-a26f-3627eb69147a} <Error> executeQuery: Code: 60. DB::Exception: Unknown table expression identifier 'system.backup_log' in scope SELECT SUM(total_size) AS total_size, SUM(uncompressed_size) AS uncompressed_size, SUM(compressed_size) AS compressed_size, formatReadableSize(total_size) AS readable_total_size, formatReadableSize(uncompressed_size) AS readable_uncompressed_size, formatReadableSize(compressed_size) AS readable_compressed_size FROM system.backup_log WHERE (status = 'BACKUP_CREATED') AND (start_time > (now() - toIntervalHour(24))). (UNKNOWN_TABLE) (version 24.11.1.1247 (official build)) (from 192.168.130.12:49968) (in query: /* { "client": "clickhouse-monitoring" } */
 SELECT SUM(total_size) as total_size, SUM(uncompressed_size) as uncompressed_size, SUM(compressed_size) as compressed_size, formatReadableSize(total_size) as readable_total_size, formatReadableSize(uncompressed_size) as readable_uncompressed_size, formatReadableSize(compressed_size) as readable_compressed_size FROM system.backup_log WHERE status = 'BACKUP_CREATED' AND start_time > (now() - INTERVAL 24 HOUR) FORMAT JSONEachRow), Stack trace (when copying this message, always include the lines below):
```
in more>backups.

**Comment by duyet** [comment]
Hi, the `backup_log` is only available when you have run a backup at least once [1]. You can just ignore that page until you need to list your backups. But thanks for your note, I may add more descriptive errors to avoid confusion.

[1] https://clickhouse.com/docs/en/operations/backup

**Comment by gregzuro** [comment]
I suspected as much.

Thanks for the attention and thanks for the app.  It's nicely done and quite helpful.
