### ISSUE TITLE
Display clickhouse-monitoring version in GUI

### ISSUE THREAD

**Issue by piotrrybicki** [duyet/clickhouse-monitoring#408]
Hi.

It would be nice to see somewhere in GUI running version of clickhouse-monitoring itself.

Perhaps not on main overview page, but under More -> About ?

Best regards
Piotr Rybicki

**Comment by duyet** [comment]
Hi @piotrrybicki, this has been implemented in https://github.com/duyet/clickhouse-monitoring/pull/409. Please let me know your thoughts.

![](https://i.imgur.com/OBi5fPl.png)

**Comment by piotrrybicki** [comment]
Looks nice. I'll test it once it is released. Thanks
