### ISSUE TITLE
Permission grants on system tables

### ISSUE THREAD

**Issue by janeklb** [duyet/clickhouse-monitoring#449]
Hello 👋🏻 

Thanks for publishing your tool -- I am exploring whether it can help me monitor my clickhouse cluster.

While reading through the [requirements docs](https://duyet.github.io/clickhouse-monitoring/getting-started/clickhouse-requirements), I noticed that the recommended setup is to create a role with lots of privileges on the system tables

specifically this query:
```xml
<query>GRANT SELECT,INSERT,ALTER,CREATE,DROP,TRUNCATE,OPTIMIZE,SHOW,dictGet ON system.*</query>
```

What are `INSERT,ALTER,CREATE,DROP,TRUNCATE` used for? and what about `OPTIMIZE`?

**Comment by duyet** [comment]
Thank you for your comment.

I have updated the docs to clarify your concerns, as the UI primarily just SELECTs from `system.*` tables.

- https://github.com/duyet/clickhouse-monitoring/pull/243 introduces a feature that requires creating and inserting into the `system.monitoring_events` table, which is configurable (https://github.com/duyet/clickhouse-monitoring/pull/357). This action needs permissions for `INSERT`, `ALTER`, `CREATE`, `DROP`, and `TRUNCATE`. I would suggest limiting the role to user-specific tables.
- There is also an `OPTIMIZE` action on the table explorer page that requires that permission.

**Comment by janeklb** [comment]
Thank you 🙇🏻
