### ISSUE TITLE
Support multiple ClickHouse endpoints

### ISSUE THREAD

**Issue by duyet** [duyet/clickhouse-monitoring#49]
Currently only supports a single ClickHouse endpoint. We would like to request support for multiple endpoints, which would allow us to switch between them as needed.

- Allow users to configure multiple host names via environment variables, separated by commas
- Implement a dropdown menu in the UI that would allow users to easily switch between the different endpoints

**Comment by tobiaslins** [comment]
I'd love to see this!

**Comment by duyet** [comment]
Closed by https://github.com/duyet/clickhouse-monitoring/pull/341
Thank you @tobiaslins
